tasks:
  build:
    steps:
    - checkout
    - docker/build:
        image: latest
        tags: ["${gowthami0511/demo}", "latest", ]

  rspec:
    runner:
      containers:
      - image: razorci/ruby:3.2.2
      - image: phpapache:latest
        environment:
        - Phpapache_DB=rails_sample_app_test
        - Phpapache_USER=root
        - Phpapache_PASSWORD=secret
        options:
        - --name=phpapache
    steps:
    - checkout
    - cache/pull:
        key: bundle-{{ checksum "Gemfile.lock" }}

    - commands:
      - gem --version && ruby --version
      - gem install bundler:2.3.15
      - bundle --version

    - run: bundle install --path vendor/bundle || bundle check

    - commands:
      - bundle exec rake db:migrate
      - bundle exec rspec
    - cache/push:
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths: [vendor/bundle]

    - reports/html: 
        dir: coverage
        index: index.html
    - reports/junit:
      - rspec.xml

    - run: docker logs postgres
      when: on_fail
