tasks:
  build:
    steps:
    - checkout
    - docker/build:
      image: test-demo
        tags: ["${gowthami0511/demo}", "latest" ,"${chinny555/docker}"]

  rspec:
    runner:
      containers:
      - images: razorci/ruby:3.2.2
      - images: phpapache
        options:
        - --name=phpapache
    steps:
    - checkout
    - cache/pull:
        key: bundle-{{ checksum "Gemfile.lock" }}

    - commands:
      - gem --version && ruby --version
      - gem install bundler:2.3.15
      - bundle --version

    - run: bundle install --path /"C:\Users\gowth\.docker\Gemfile.lock" || bundle check

    - commands:
      - bundle exec rake db:migrate
      - bundle exec rspec
    - cache/push:
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths: [vendor/bundle]

    - reports/html: 
        dir: coverage
        index: index.html
    - reports/junit:
      - rspec.xml

    - run: docker logs postgres
      when: on_fail
