tasks:
  build-image:
    steps:
    - checkout
    - run: bundle install
    - commands:
      - gem --version && ruby --version
      - gem install bundler:2.3.15
      - bundle --version

    - run: bundle install --path vendor/bundle || bundle check

    - commands:
      - bundle exec rake db:migrate
      - bundle exec rspec
    - docker/build:
       images: razorci/phpapache
       images: phpapache:latest
       push: true
       tags: ["${CI_COMMIT_SHA:0:8}", "latest"]
       dockerfile: Dockerfile
       context: .
       args:
       - API_TOKEN=zOT+zClNU8Bv3yiEfQPkrA==
