tasks:
  build-image:
    steps:
    - checkout
    - run: bundle install
    - commands:
        - docker images
        - docker push gowthami0511/demo:latest
    - docker/build:
       image: razorci/phpapache
       push: true
       tags: ["${phpapache}", "latest"]
       dockerfile: Dockerfile
       context: .
       args:
       - API_TOKEN=zOT+zClNU8Bv3yiEfQPkrA==
