tasks:
  build-image:
    steps:
    - checkout
    - docker/build:
       images: razorci/ruby 3.2.2
       images: phpapache:latest
       push: true
       tags: ["${CI_COMMIT_SHA:0:8}", "latest"]
       dockerfile: Dockerfile
       context: .
       args:
       - API_TOKEN=zOT+zClNU8Bv3yiEfQPkrA==
